# Generated by Django 4.0.3 on 2022-04-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tweet_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='key',
            field=models.CharField(db_index=True, max_length=66),
        ),
    ]
